# Generated by Django 4.0.10 on 2024-08-02 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('traffic_condition', models.CharField(choices=[('clear', 1), ('moderate', 5), ('heavy', 10)], max_length=10)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_roads', to='api.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_roads', to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('traffic_condition', models.CharField(choices=[('clear', 1), ('moderate', 5), ('heavy', 10)], max_length=10)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='api.road')),
            ],
        ),
        migrations.DeleteModel(
            name='ScehduleEmail',
        ),
    ]
