# Generated by Django 4.0.10 on 2024-08-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_end_location_road_end_location_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='road',
            old_name='end_location_id',
            new_name='end_location',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='start_location_id',
            new_name='start_location',
        ),
    ]
